### PR TITLE
Fix typo on Scott Chacon name and book

### PR DESCRIPTION
**Pull request by sleeper**
The book is about Git (not Github), and the author is S. Chacon ;)

### CODE REVIEW

**Comment by bgentry** [comment]
@sleeper can you get rid of the newline diff at the end of the commit? otherwise :+1:

**Comment by sleeper** [comment]
Oki doki ... removed ;)

**Comment by schof** [comment]
Was going to submit my own pull request for this but of course ... someone has already done it for me

**Comment by WiredEnterprise** [comment]
Thanks. I think we got these.

**Comment by sleeper** [comment]
Well, actually the Scott Chacon part is merged, but not the fact that his book is on Git and not Github ;)

**Comment by WiredEnterprise** [comment]
Right you are. My mistake. Thanks for pointing that out.

**Comment by sleeper** [comment]
No issue ;)

**Pull request closed without merging**
