### PR TITLE
Better narrative

### PR DESCRIPTION
**Pull request by maddox**
This pull removes the portions telling the history of Git and how it works. This leaves a better overall narrative about GitHub.

### CODE REVIEW

**Comment by enginoid** [comment]
LGTM!

**Comment by dominicsayers** [comment]
The bit about gatekeepers is also wrong. Whoever pulls a pull request is a gatekeeper. If there were no Sacred Gatekeepers with git and GitHub this fork would have been merged by now.

**Comment by WiredEnterprise** [comment]
Well it's to the point. I'll give it that.

**Comment by dominicsayers** [comment]
QED

**Pull request closed without merging**
